# standard jekyll configuration

permalink: date
pygments: false
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount

# configuration required for some pages

domain: www.thebigjc.org
title: Jordan Christensen&apos;s blog o fun
author: Jordan Christensen
email: jordan@thebigjc.org

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

google_analytics:
   account: UA-1388949-1

github:
  username: thebigjc

facebook: 
  id: 500149926
	
# disqus:
#   id: disqusid
